# Write your MySQL query statement below
SELECT P.PRODUCT_ID, P.PRODUCT_NAME
FROM SALES AS S
JOIN PRODUCT AS P
ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID NOT IN (SELECT S.PRODUCT_ID
                         FROM SALES AS S
                         WHERE S.SALE_DATE NOT BETWEEN '2019-01-01' AND '2019-03-31')
GROUP BY P.PRODUCT_ID